apiVersion: v1
kind: Service
metadata:
  name: centaur-os
  labels:
    app.kubernetes.io/name: centaur-os
    app.kubernetes.io/version: "0.1.0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: centaur-os
  ports:
    - name: agent
      port: 8081
      targetPort: agent
    - name: ingest
      port: 8082
      targetPort: ingest
