apiVersion: v1
kind: Service
metadata:
  name: centaur-context
  labels:
    app.kubernetes.io/name: centaur-context
    app.kubernetes.io/version: "0.3.0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: centaur-context
  ports:
    - name: agent
      port: 8081
      targetPort: agent
    - name: ingest
      port: 8082
      targetPort: ingest
---
apiVersion: v1
kind: Service
metadata:
  name: centaur-context-note-write
  labels:
    app.kubernetes.io/name: centaur-context
    app.kubernetes.io/version: "0.3.0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: centaur-context
  ports:
    - name: note-write
      port: 8084
      targetPort: note-write
